def main():
    print('1. cyclops')
    print("2. goblin")
    print('3. wizard')
    print("4. snail")
    print("5. troll")
    print("6. village")
    print("7. forest")
    print("8. mountains")
    print("9. tower")
    user_imput = input()
    if user_imput == "1":
        print("there is a big ugly cyclops in front of Vasalisa")
        print(".-'  ____  `-.")
        print("( ( (_()_)  ) ")
        print("`-.   ^^   .-'")
        print("   `._==_.'")
        print("    __)(___)" )


    elif user_imput == "2":
        print("There is an ugly goblin in front of Vasalisa")
        print("|\  \/      \/  /|")
        print("| \ / =.  .= \ / |")
        print("\( \   o\/o   / )/")
        print(" \_, '-/  \-' ,_/")
        print("   /   \__/   \  ")
        print("   \,___/\___,/  ")
        print(" ___\ \|--|/ /___")
        print("     \      /    ")
        print("      '----'       ")

    elif user_imput == "3":
        print("The Evil Wizard stand before Vasalisa")
        print(" |\          .(' *) ' .")
        print(" | \        ' .*) .'*")
        print(" |(*\      .*(// .*) .")
        print(" |___\       // (. '*")
        print(" (((\"'\     // '  * .")
        print(" ((c'7')   //)")
        print(" ((((^))  /  |")
        print("-')))(((-'/")
        print(" (((()) __/'")
        print("  )))( |")
        print("  (()")

    elif user_imput == "4":
        print("There is a giant snail in front of Vasalisa")
        print("     .----.   @   @ ")
        print("   / .-\"-.`.   \ /")
        print("   | | ('\ \ \_/ )")
        print("  ,-\ `-.' /.'  /")
        print(" '---`----'----'")

    elif user_imput == '5':
        print("There is an ugly troll in front of Vasalisa")
        print(" __,='`````'=/__")
        print(" '// (o) \(o) \ `' ")
        print("//|     ,_)   (`\ ")
        print("~~~\  `'==='  /-, ")
        print("      `----'     `") 

    elif user_imput == '6':
        print('Vasalisa is in a village')
        print("            |   _   _")
        print("      . | . x .|.|-|.|")
        print("   |\ ./.\-/.\-|.|.|.|")
        print("~~~|.|_|.|_|.|.|.|_|.|~~~")

    elif user_imput == '7':
        print("Vasalisa is in a forest")
        print(" ^  ^   ^  ^  ^   ^  ^")
        print("/|\/|\ /|\/|\/|\ /|\/|\ ")
        print("/|\/|\ /|\/|\/|\ /|\/|\ ")
        print("/|\/|\ /|\/|\/|\ /|\/|\ ")
    
    elif user_imput == '8':
        print('Vasalisa is the mountains')
        print("   /\    /\  /\      /\            /\/\/\  ")
        print("  /  \/\/  \/  \  /\/  \/\  /\  /\/ / /  \ ")
        print(" /    \ \  /    \/ /   /  \/  \/  \  /    \   ")
        print("/      \  /     /          \ ")
    
    elif user_imput == '9':
        print('Vasalisa is at the tower of the evil wizard')
        print('     |>>>')
        print('     |')
        print(' _  _|_  _')
        print('|;|_|;|_|;|')
        print('\.     .  /')
        print(' \:  .   /')
        print('  ||:   |')
        print('  ||:.  |')
        print('  ||:  .|')
        print('  ||:   |')
        print('  ||: , |')
        print('  ||:   |')
        print('  ||: . |')
        print('__||_   |')
main()